### PR TITLE
VirtualTimeScheduler and time API split

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

**Comment by sdeleuze** [comment]
I like the `withVirtualTime()` approach, but I am not sure about forcing users to provide a `Supplier` of `Publisher` in `verify()`. I have updated all the Lite Rx API Hands-On without facing such issue.

@bclozel Any take on this? Did you faced such issue while porting the huge number of tests in Spring Framework?

**Comment by simonbasle** [comment]
@sdeleuze yeah, I agree this can seem like a big constraint (esp. for existing tests refactoring). the idea was to avoid rewriting the whole implementation: here the concrete classes are all implementing the virtual-time specialized interface and are simply exposed as the simpler interface when using `create`...

The alternatives would be:

1. duplicate almost the whole hierarchy of subscriber and builders in order to have one side that sets up the `VirtualTimeScheduler` then allows to manipulate it, but forces the user to defer the providing of `Publisher` (so that tested publishers have a chance to pick up the virtual time scheduler). the other side wouldn't care about the virtual clock and thus authorize `verify` calls with a pre-existing `Publisher`...
2. leave it entirely to the user to guess the correct usage pattern, don't activate the `VirtualTimeScheduler` in the subscriber's factory method and expect the user to enable it out-of-band, before he/she creates the `Publisher` to be tested. This way the virtual time method are still only available when using the `withVirtualTime` factory method, but it can be used in an illegal state (virtual clock is not enabled), which is what I tried to avoid...

**Comment by smaldini** [comment]
Thanks @simonbasle  for giving this a try. As much as I found the idea appealing to avoid enable/disable dance, I don't find the two alternatives solid enough wrt solving user experience. There are 3 other alternatives : 
- Current one with improved feedback (error could be raised if enableVirtualTime has not been called much sooner). Given the constraints established in @simonbasle comment it's not the worst solution IMO
- using ```ScriptedSubscriber.withVirtualTime(Function<SciptedSubscriberWithTimeBuilder, Publisher>, options)```. With a delimiting callback/block we can auto start/release the VirtualTimeScheduler around the callback. It might makes things more clear if we give a scope to user like this callback where they can actually play with virtual time.
- remove advanceTime from ScriptedSubscriber and offer as proposed in #20 an arbitrary run script where you could do :  ```ScriptedSubscriber.create().run(() -> VirtualTimeScheduler.advanceTime(ofSeconds(4))```

**Comment by smaldini** [comment]
Note that alternative 2 and 3 in my previous comment are not mutually exclusive.

**Comment by simonbasle** [comment]
I have further tried to separate concerns where virtual time is used (in which case the tested flux's creation must be deferred in order for it to pick up the `VirtualTimeScheduler`) from the usual case where virtual time isn't used.

This leads to some code duplication, but has the benefit of not exposing the `advanceTimeByXXX` methods where they don't make sense, plus enabling/disabling the `VirtualTimeScheduler` is taken care of for you.

For now I have pushed that into a [sub-branch](https://github.com/reactor/reactor-addons/tree/tests/25b-scriptedWithTimeDuplicateAPI)

**Comment by smaldini** [comment]
Reworked in #31

**Pull request closed without merging**
