### PR TITLE
use retryWhen directly in Mono to get the correct method signature.

### PR DESCRIPTION
**Pull request by bjartek**
Do we needs more tests here or is this good?

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bjartek Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-addons&pullRequestId=152)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-addons&pullRequestId=152) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@bjartek Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-addons&pullRequestId=152)!

**Comment by bjartek** [comment]
fixes #151

**Comment by simonbasle** [comment]
should be good in terms of tests, unless you want to explicitly declare a var in the `RetryExtensionTest` as `Mono` to check the retry extension does indeed return a `Mono`?

**Comment by bjartek** [comment]
Good point, I refactored the tests and used explicit typing on the return values to make sure they are monos.

**Comment by simonbasle** [comment]
looking good, thanks for the PR 🎁 @bjartek 👍

**Pull request merged**
